### ISSUE TITLE
ImportError: cannot import name 'ModelField' from 'pydantic.fields'

### ISSUE THREAD

**Issue by Bmgpt** [ciuzaak/Claude-Telegram-Bot#12]
I have Deployed these latest repositories on Zeabur. However, I got this error on Runtime Logs. Please help me.

ImportError: cannot import name 'ModelField' from 'pydantic.fields' (/usr/local/lib/python3.11/site-packages/pydantic/fields.py)

<img width="666" alt="Screenshot 2023-07-01 at 9 36 57 AM" src="https://github.com/ciuzaak/Claude-Telegram-Bot/assets/137195478/c678de31-392a-4ab1-86cd-94f5fc236b24">

**Comment by ciuzaak** [comment]
It should be solved. Please update the repository and redeploy it.
