### ISSUE TITLE
Error orrurred: SNlM0e value not found in response. Check __Secure-1PSID value..

### ISSUE THREAD

**Issue by laraws** [ciuzaak/Claude-Telegram-Bot#13]
I have filled my bard Secure-1PSID value in config.yaml, and the bot was working fine before. However, recently the bot always responds with the error message 'Error occurred: SNlM0e value not found in response. Check Secure-1PSID value..'. Please fix this issue. Thank you.

**Comment by ciuzaak** [comment]
The Secure-1PSID may expire after a certain period of time. You would need to retrieve it again from your browser and fill it in. Please follow the steps you took originally to get the Secure-1PSID, then update the value in the config.yaml file. After updating, restart your bot and see if this resolves the issue.

**Comment by ciuzaak** [comment]
Have you restarted the bot? And please make sure you use the newest code.

**Comment by laraws** [comment]
> Have you restarted the bot? And please make sure you use the newest code.

It works after I change the key to another account's one. Thx.
