### ISSUE TITLE
Error orrurred: 'factualityQueries'.

### ISSUE THREAD

**Issue by laraws** [ciuzaak/Claude-Telegram-Bot#14]
My bard cookie key is up-to-date. After configuring it in the config file and using the bot for approximately 3 messages, it works fine. However, it consistently responds with the error message 'Error occurred: factualityQueries' afterwards.

Please fix it. Thanks.

**Comment by ciuzaak** [comment]
Me too. Looks like Bard blocked the reversed engineered API? 😂

**Comment by ciuzaak** [comment]
> My bard cookie key is up-to-date. After configuring it in the config file and using the bot for approximately 3 messages, it works fine. However, it consistently responds with the error message 'Error occurred: factualityQueries' afterwards.
> 
> Please fix it. Thanks.

This is the [solution](https://github.com/dsdanielpark/Bard-API/issues/97#issuecomment-1632451009).

I just clean all cookies related to Bard page, copy the newest PSID, and it works.

![image](https://github.com/ciuzaak/Claude-Telegram-Bot/assets/41275670/4d1e5d02-70ce-476e-ac69-2b8911fba041)

**Comment by laraws** [comment]
> 

Thank you for providing a solution. I initially tried it and it worked for the first 3 attempts, but unfortunately, it doesn't seem to work anymore. Is your bot still functional at present?

**Comment by ciuzaak** [comment]
> > 
> 
> Thank you for providing a solution. I initially tried it and it worked for the first 3 attempts, but unfortunately, it doesn't seem to work anymore. Is your bot still functional at present?

Mine works well. Try cleaning all cookies related to Google Bard including `account.google.com`, `www.google.com` ... ?

**Comment by ciuzaak** [comment]
> > 
> 
> Thank you for providing a solution. I initially tried it and it worked for the first 3 attempts, but unfortunately, it doesn't seem to work anymore. Is your bot still functional at present?


Seems I have found a good solution: open the browser in InPrivate mode, then open Bard and obtain the 1psid.

**Comment by laraws** [comment]
> > > 
> > 
> > 
> > Thank you for providing a solution. I initially tried it and it worked for the first 3 attempts, but unfortunately, it doesn't seem to work anymore. Is your bot still functional at present?
> 
> Seems I have found a good solution: open the browser in InPrivate mode, then open Bard and obtain the 1psid.

Great. I'll try. 👍

**Comment by laraws** [comment]
> > > 
> > 
> > 
> > Thank you for providing a solution. I initially tried it and it worked for the first 3 attempts, but unfortunately, it doesn't seem to work anymore. Is your bot still functional at present?
> 
> Seems I have found a good solution: open the browser in InPrivate mode, then open Bard and obtain the 1psid.

Great. It works ok.👍️
