### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Sksk2999** [ciuzaak/Claude-Telegram-Bot#15]
how allow access to all users?

**Comment by ciuzaak** [comment]
https://github.com/ciuzaak/Claude-Telegram-Bot/blob/f9a2495b375c7052a291062a34562f2aae64335d/bot.py#L380

Change to:
```python
user_filter = filters.CHAT
```

But I wouldn't recommend doing that, because both Claude and Bard have rate limits, and their usage by multiple people could potentially cause conflicts. 😓

**Comment by Sksk2999** [comment]
Thanks
