### ISSUE TITLE
请问如何获取Google Bard的__Secure-1PSIDTS

### ISSUE THREAD

**Issue by Van426326** [ciuzaak/Claude-Telegram-Bot#21]
![image](https://github.com/ciuzaak/Claude-Telegram-Bot/assets/33017677/ece8dff1-aa72-4006-b224-ef8e335a0d65)

**Comment by Van426326** [comment]
__Secure开头的只有这些

**Comment by ciuzaak** [comment]
用无痕试试？

**Comment by TheSL18** [comment]
use the psi1dcc its works
