### ISSUE TITLE
need help 

### ISSUE THREAD

**Issue by GoodJoey** [ciuzaak/Claude-Telegram-Bot#4]
i failed to sign in "https://console.anthropic.com/claude"
erros shows "You do not currently have a valid Anthropic account. You may need to accept your invite: check for an email with the subject “Your invitation to Claude, from Anthropic” and click the link there."

so , is that means i need someonelse' invitation?

**Comment by ciuzaak** [comment]
You do not require an invitation from anyone else. You simply need to apply on this [website](https://www.anthropic.com/earlyaccess). Typically within one to two weeks, you will receive an email (example below) notifying you that your application has been approved. Subsequently, you will be able to access Claude's console and API.
![image](https://user-images.githubusercontent.com/41275670/233005907-c8ba26ea-5c8f-41b8-ae7a-4aedb7502dcf.png)
