### ISSUE TITLE
Bard only access not giving responses

### ISSUE THREAD

**Issue by arnab3k** [ciuzaak/Claude-Telegram-Bot#5]
I have access to Bard but not Claude and it doesn't return any response if I change mode using /mode

Any easy way to figure out what exactly is wrong?

**Comment by ciuzaak** [comment]
I think it should be Bard's authentication error? Make sure you have properly obtained the authentication following this:

## Authentication
Go to https://bard.google.com/

- F12 for console
- Copy the values
  - Session: Go to Application → Cookies → `__Secure-1PSID`. Copy the value of that cookie.

**Don't forget the `.` at the end of `__Secure-1PSID`.**

When you provide incorrect authentication, using `/mode` should give you the console output `[e] 'NoneType' object has no attribute 'group'`.
