### ISSUE TITLE
Feature request 'Poe'

### ISSUE THREAD

**Issue by m-kaissi** [ciuzaak/Claude-Telegram-Bot#6]
can you add support for Poe platform which include some useful AI bots, here's the api https://github.com/ading2210/poe-api

**Comment by ciuzaak** [comment]
Hi there,

As I don't use Poe frequently, I currently do not have any plans to include Poe functionality. However, you may want to try out this [repository](https://github.com/TBXark/poe-telegram-bot) as an alternative solution.

**Comment by m-kaissi** [comment]
Thanks bro for your time and hard word , and also for the repo you recommended for me
