### ISSUE TITLE
Error orrurred, please try again later. Your chat history has been reset.

### ISSUE THREAD

**Issue by garywu520** [ciuzaak/Claude-Telegram-Bot#7]
When I am use Telegram Bot sent massage, error: 
```
"Error orrurred, please try again later. Your chat history has been reset.", 
```

Error in Docker: 
```
[+] bot started, calling loop!
[e] ('post request failed with status code: 401', {'detail': 'Invalid API Key'}) 
```

I'm sure my Google Bard cookie __Secure-1PSID value is correct. so how to do?
Thanks.

**Comment by ciuzaak** [comment]
This type of error is only returned by Claude, so I guess you entered Google Bard's cookie __Secure-1PSID in the place of the Claude API......

**Comment by garywu520** [comment]
I do only have Bard, but its default mode is Claude, because Claude is empty, so the message replies Error, I have switched the mode, and now I am using Bard normally, thanks for the reply

However, it is suggested that you can add mode options during the docker build process to force the designation of Bard or Claude or both, if you think it makes sense.

**Comment by ciuzaak** [comment]
Thanks for the suggestion! 

Actually I have already added a `default_mode` variable in `config/__init__.py`:

```python
default_mode = 'Claude' if claude_api is not None else 'Bard'
```

When the user can only access one mode, it will automatically be set as the default mode. When the user can access both modes, Claude is set as the default. In theory, the situation you described should not happen. I will double check again😂

**Comment by garywu520** [comment]
My Config YAML, I hope if it can help you check.
```yaml
telegram:
  bot_name: 'My_AI'
  token: 'xxxxxxxxxxx'
  username: '[xxxxxx]'
claude:
  api: ''
bard:
  api: 'xxxxxxxxxxxxxx.'
```

**Comment by ciuzaak** [comment]
Oh I see... You just need to remove the '', because in this case it will recognize claude_api as an empty string rather than None.
