### ISSUE TITLE
use '/mode' change bard no response

### ISSUE THREAD

**Issue by garywu520** [ciuzaak/Claude-Telegram-Bot#8]
Hi, Fast Restoration problem:
1. Telegram send message
```
/mode
```

2. Docker container log error
```
[+] bot started, calling loop!

[e] 'NoneType' object has no attribute 'group'
```

My environment:
There is currently no Claude API, so the option is left blank.
Only the Bard API is filled.

**Comment by ciuzaak** [comment]
Hi,

When only Claude or Bard API is filled in, sending `/mode` will reply with '❌ You cannot access the other mode'. Here is the code:

```python
async def change_mode(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if single_mode:
        await update.message.reply_text(f'❌ You cannot access the other mode.')
        return
    ......
```
 
Please make sure you have removed all `'` from the `config/config.yml`, and the Bard API is valid (because clearing the browser cookies may invalidate it).

**Comment by garywu520** [comment]
Th.
